import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgStyle } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, NgStyle],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Thero Studio';

  design = {
    primaryColor: '#4f46e5',
    secondaryColor: '#ec4899',
    backgroundColor: '#f9fafb',
    surfaceColor: '#ffffff',
    textColor: '#111827',
    mutedTextColor: '#6b7280',
    fontFamilyBody:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyHeading: '"Georgia", "Times New Roman", serif',
    baseFontSize: 16,
    spacingUnit: 8,
    borderRadius: 8
  };

  get previewStyles() {
    return {
      '--primary-color': this.design.primaryColor,
      '--secondary-color': this.design.secondaryColor,
      '--background-color': this.design.backgroundColor,
      '--surface-color': this.design.surfaceColor,
      '--text-color': this.design.textColor,
      '--muted-text-color': this.design.mutedTextColor,
      '--font-body': this.design.fontFamilyBody,
      '--font-heading': this.design.fontFamilyHeading,
      '--base-font-size': this.design.baseFontSize + 'px',
      '--spacing-unit': this.design.spacingUnit + 'px',
      '--border-radius': this.design.borderRadius + 'px'
    } as { [key: string]: string };
  }

  downloadCss() {
    const css = this.generateCss();
    const blob = new Blob([css], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'styleguide.css';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  private generateCss(): string {
    const d = this.design;
    return [
      '/* Generated by Thero Studio */',
      ':root {',
      `  --primary-color: ${d.primaryColor};`,
      `  --secondary-color: ${d.secondaryColor};`,
      `  --background-color: ${d.backgroundColor};`,
      `  --surface-color: ${d.surfaceColor};`,
      `  --text-color: ${d.textColor};`,
      `  --muted-text-color: ${d.mutedTextColor};`,
      `  --font-body: ${d.fontFamilyBody};`,
      `  --font-heading: ${d.fontFamilyHeading};`,
      `  --base-font-size: ${d.baseFontSize}px;`,
      `  --spacing-unit: ${d.spacingUnit}px;`,
      `  --border-radius: ${d.borderRadius}px;`,
      '}',
      '',
      'body {',
      '  font-family: var(--font-body);',
      '  font-size: var(--base-font-size);',
      '  color: var(--text-color);',
      '  background-color: var(--background-color);',
      '}',
      '',
      '.btn-primary {',
      '  background-color: var(--primary-color);',
      '  color: #ffffff;',
      '  border-radius: var(--border-radius);',
      '  padding: calc(var(--spacing-unit) * 0.75) calc(var(--spacing-unit) * 1.5);',
      '}',
      '',
      '.card {',
      '  background-color: var(--surface-color);',
      '  border-radius: var(--border-radius);',
      '  padding: calc(var(--spacing-unit) * 2);',
      '  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.1);',
      '}',
      ''
    ].join('\n');
  }
}
