import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgStyle, NgFor } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, NgStyle, NgFor],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Thero Studio';

  stylePresets = [
    {
      id: 'modern-rounded',
      label: 'Modern rounded',
      changes: {
        borderRadius: 12,
        spacingUnit: 10,
        fontFamilyHeading: '"Inter", system-ui, sans-serif'
      }
    },
    {
      id: 'minimal-sharp',
      label: 'Minimal sharp',
      changes: {
        borderRadius: 2,
        spacingUnit: 8,
        fontFamilyHeading: '"Roboto", system-ui, sans-serif'
      }
    },
    {
      id: 'editorial-soft',
      label: 'Editorial soft',
      changes: {
        borderRadius: 16,
        spacingUnit: 12,
        fontFamilyHeading: '"Georgia", "Times New Roman", serif'
      }
    }
  ];

  currentStyle = this.stylePresets[0].id;

  design = {
    primaryColor: '#4f46e5',
    secondaryColor: '#ec4899',
    accentColor: '#f59e0b',
    successColor: '#22c55e',
    errorColor: '#ef4444',
    warningColor: '#eab308',
    backgroundColor: '#f9fafb',
    surfaceColor: '#ffffff',
    textColor: '#111827',
    mutedTextColor: '#6b7280',
    fontFamilyBody:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyHeading: '"Georgia", "Times New Roman", serif',
    baseFontSize: 16,
    spacingUnit: 8,
    borderRadius: 8
  };

  locks: { [key: string]: boolean } = {
    primaryColor: false,
    secondaryColor: false,
    accentColor: false,
    successColor: false,
    errorColor: false,
    warningColor: false,
    textColor: false,
    mutedTextColor: false
  };

  get previewStyles() {
    return {
      '--primary-color': this.design.primaryColor,
      '--secondary-color': this.design.secondaryColor,
      '--accent-color': this.design.accentColor,
      '--success-color': this.design.successColor,
      '--error-color': this.design.errorColor,
      '--warning-color': this.design.warningColor,
      '--background-color': this.design.backgroundColor,
      '--surface-color': this.design.surfaceColor,
      '--text-color': this.design.textColor,
      '--muted-text-color': this.design.mutedTextColor,
      '--font-body': this.design.fontFamilyBody,
      '--font-heading': this.design.fontFamilyHeading,
      '--base-font-size': this.design.baseFontSize + 'px',
      '--spacing-unit': this.design.spacingUnit + 'px',
      '--border-radius': this.design.borderRadius + 'px'
    } as { [key: string]: string };
  }

  applyStylePreset(presetId: string) {
    this.currentStyle = presetId;
    const preset = this.stylePresets.find((p) => p.id === presetId);
    if (!preset) {
      return;
    }

    this.design = {
      ...this.design,
      ...preset.changes
    };
  }

  randomizeColors() {
    const keys = [
      'primaryColor',
      'secondaryColor',
      'accentColor',
      'successColor',
      'errorColor',
      'warningColor',
      'textColor',
      'mutedTextColor'
    ] as const;

    keys.forEach((key) => {
      if (!this.locks[key]) {
        (this.design as any)[key] = this.randomHexColor();
      }
    });
  }

  toggleLock(key: string) {
    this.locks[key] = !this.locks[key];
  }

  private randomHexColor(): string {
    const value = Math.floor(Math.random() * 0xffffff)
      .toString(16)
      .padStart(6, '0');
    return `#${value}`;
  }

  downloadCss() {
    const css = this.generateCss();
    const blob = new Blob([css], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'styleguide.css';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  private generateCss(): string {
    const d = this.design;
    return [
      '/* Generated by Thero Studio */',
      ':root {',
      `  --primary-color: ${d.primaryColor};`,
      `  --secondary-color: ${d.secondaryColor};`,
       `  --accent-color: ${d.accentColor};`,
       `  --success-color: ${d.successColor};`,
       `  --error-color: ${d.errorColor};`,
       `  --warning-color: ${d.warningColor};`,
      `  --background-color: ${d.backgroundColor};`,
      `  --surface-color: ${d.surfaceColor};`,
      `  --text-color: ${d.textColor};`,
      `  --muted-text-color: ${d.mutedTextColor};`,
      `  --font-body: ${d.fontFamilyBody};`,
      `  --font-heading: ${d.fontFamilyHeading};`,
      `  --base-font-size: ${d.baseFontSize}px;`,
      `  --spacing-unit: ${d.spacingUnit}px;`,
      `  --border-radius: ${d.borderRadius}px;`,
      '}',
      '',
      'body {',
      '  font-family: var(--font-body);',
      '  font-size: var(--base-font-size);',
      '  color: var(--text-color);',
      '  background-color: var(--background-color);',
      '}',
      '',
      '.btn-primary {',
      '  background-color: var(--primary-color);',
      '  color: #ffffff;',
      '  border-radius: var(--border-radius);',
      '  padding: calc(var(--spacing-unit) * 0.75) calc(var(--spacing-unit) * 1.5);',
      '}',
      '',
      '.card {',
      '  background-color: var(--surface-color);',
      '  border-radius: var(--border-radius);',
      '  padding: calc(var(--spacing-unit) * 2);',
      '  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.1);',
      '}',
      '',
      '.badge-accent {',
      '  background-color: var(--accent-color);',
      '  color: #ffffff;',
      '  border-radius: 999px;',
      '  padding: 0.25rem 0.75rem;',
      '}',
      '',
      '.text-success {',
      '  color: var(--success-color);',
      '}',
      '',
      '.text-error {',
      '  color: var(--error-color);',
      '}',
      '',
      '.text-warning {',
      '  color: var(--warning-color);',
      '}',
      ''
    ].join('\n');
  }
}
